jdeferred/jdeferred

README.md

Hi
I add how install for gradle in README.
Thanks.

add how install for gradle

---

core/pom.xml
core/src/main/java/org/jdeferred/CancellablePromise.java
core/src/main/java/org/jdeferred/impl/DefaultCancellablePromise.java
core/src/main/java/org/jdeferred/impl/DelegatingPromise.java
core/src/test/java/org/jdeferred/impl/CancellablePromiseTest.java
parent/pom.xml

Added a base Promise type that enables easy delegation.
Fix for #39

Added cancel capability to Promise.

---

.travis.yml

Added Travis configuration

---

README.md
core/src/main/java/org/jdeferred/DeferredManager.java

Fixing DeferredManager.StartPolicy.MANAUL Bad spelling

---

subprojects/jdeferred-android/jdeferred-android.gradle

Uncommented dependency needs in JDeferred Android subproject

---

subprojects/jdeferred-android/jdeferred-android.gradle

Force Java 1.6 compatibility

---

README.md

For https://github.com/jdeferred/jdeferred/issues/109

Moved Lambda and Groovy section up

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java

For #115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/120)

2.x - Removed deprecated functionalities

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/Deferred.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredCallable.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredFutureTask.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredRunnable.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DoneCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DoneFilter.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DonePipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailFilter.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailPipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressFilter.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressPipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractPromise.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DeferredObject.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/125)

Various javadoc updates

---

subprojects/jdeferred-android/src/main/java/org/jdeferred/android/DeferredAsyncTask.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/132)

Add CancellationHandler support to DeferredAsyncTask

---

subprojects/jdeferred-android/src/main/java/org/jdeferred/impl/DefaultAndroidDeferredManager.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/MasterDeferredObjectUntypedN.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/MutableMultipleResultsUntypedN.java
subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/MultiplePromisesTest.java

For #115 #104 /cc @SimY4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/121)

2.x Ability to take Iterable based on #104

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/DeferredManager.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractDeferredManager.java
subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/RaceTest.java
subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/SettleTest.java

Fix rejection testcases for race
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/133)

Add iterable support for race/settle.

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/multiple/MultipleResults.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/141)

Remove mutator from MultipleResults

---

build.gradle
gradle.properties
subprojects/jdeferred-android/jdeferred-android.gradle
subprojects/jdeferred-core/jdeferred-core.gradle

Report can be obtained by executing `gradle compatibilityReport`. The report fill be written to `${rootdir}/build/reports/clirr/compatibility-report.html`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/142)

Configure compatibility report via Clirr

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DeferredPromise.java

fixes #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/144)

simplify DeferredPromise by extending DelegatingPromise

---

subprojects/jdeferred-core/jdeferred-core.gradle

Fix for #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/147)

Configure Auto-Module-Name Manifest entry for jdeferred-core JAR

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/DonePipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailPipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressPipe.java

part of #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/150)

improve javadoc for the Pipe interfaces

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/DoneFilter.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailFilter.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressFilter.java

par of #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/151)

improve javadoc for the Filter interfaces

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java

part of #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/149)

improve javadoc and fix some warnings for Promise interface

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/DoneCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/FailCallback.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/ProgressCallback.java

part of #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/152)

improve javadoc for the Callback interfaces

---

subprojects/jdeferred-core/src/main/java/org/jdeferred/AlwaysPipe.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/Promise.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/AbstractPromise.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/DelegatingPromise.java
subprojects/jdeferred-core/src/main/java/org/jdeferred/impl/PipedPromise.java
subprojects/jdeferred-core/src/test/java/org/jdeferred/impl/PipedPromiseTest.java

resolves #153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/155)

add AlwaysPipe

---

README.md

Fixes #145 /cc @rgra
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/159)

Updated README to reflect proper coordinates for Gradle

---

README.md

Fixed typos and stuff and carried over changes from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/161)

Updated README for 2.x

---

build.gradle
gradle.properties
subprojects/jdeferred-android/jdeferred-android.gradle
subprojects/jdeferred-core/jdeferred-core.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/164)

Configure automatic push to maven central

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/170)

Updated README to call out the change from then to pipe/filter

---

DEVELOPMENT.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jdeferred/jdeferred/171)

Updated DEVELOPMENT instructions
